// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYarjtb7T-8nQdo3VnuNIKa08lmZq3Fl8',
    appId: '1:18222945633:web:f0c568d2965d172c17e120',
    messagingSenderId: '18222945633',
    projectId: 'meeting-organizer-3e118',
    authDomain: 'meeting-organizer-3e118.firebaseapp.com',
    storageBucket: 'meeting-organizer-3e118.appspot.com',
    measurementId: 'G-3WX40E7T54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8jT_3rZcmcb4u7ii3v22_kP4SFcMR4Iw',
    appId: '1:18222945633:android:f01cfaf4e1918b2217e120',
    messagingSenderId: '18222945633',
    projectId: 'meeting-organizer-3e118',
    storageBucket: 'meeting-organizer-3e118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbKicO-kp75nFy9nCg074Q5s-eFHQa7Lw',
    appId: '1:18222945633:ios:c9a9b0b4a92b58fb17e120',
    messagingSenderId: '18222945633',
    projectId: 'meeting-organizer-3e118',
    storageBucket: 'meeting-organizer-3e118.appspot.com',
    iosClientId: '18222945633-3mjo8gckdfg4tmbhni0svk0b7ua42juv.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetingOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbKicO-kp75nFy9nCg074Q5s-eFHQa7Lw',
    appId: '1:18222945633:ios:c9a9b0b4a92b58fb17e120',
    messagingSenderId: '18222945633',
    projectId: 'meeting-organizer-3e118',
    storageBucket: 'meeting-organizer-3e118.appspot.com',
    iosClientId: '18222945633-3mjo8gckdfg4tmbhni0svk0b7ua42juv.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetingOrganizer',
  );
}
